---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM default minimum permissions boundary'
Metadata:
  Template:
    Project: !Ref Project
    Revision: !Ref Revision

Parameters:
  Project:
    Description: An identifier for the project this stack is associated with.
    Type: String
  Revision:
    Description: The git short hash of the repo when the template was applied.
    Type: String

Resources:
  DefaultPermissionsBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DefaultPermissionsBoundary
      Path: /PermissionsBoundaries/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action:
              - iam:CreateOpenIDConnectProvider
              - iam:UpdateOpenIDConnectProviderThumbprint
              - iam:AddClientIDToOpenIDConnectProvider
              - iam:RemoveClientIDFromOpenIDConnectProvider
              - iam:DeleteOpenIDConnectProvider
            Resource: '*'

# Prevent modification of the permissions boundary
          - Effect: Deny
            Action:
              - iam:CreatePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:policy/PermissionsBoundaries/*

# Prevent privilege escalation
          - Effect: Deny
            Action:
              - iam:CreateRole
              - iam:CreateUser
              - iam:PutRolePermissionsBoundary
              - iam:PutUserPermissionsBoundary
            Condition:
              StringNotEquals:
                iam:PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/PermissionsBoundaries/DefaultPermissionsBoundary
            Resource: '*'
          - Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
              - iam:DeleteUserPermissionsBoundary
            Resource: '*'

# Default allow
          - Effect: Allow
            Action: '*'
            Resource: '*'
