---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM User for administration use with MFA enforced'
Metadata:
  Template:
    Project: !Ref Project
    Revision: !Ref Revision

Parameters:
  Project:
    Description: An identifier for the project this stack is associated with.
    Type: String
  Revision:
    Description: The git short hash of the repo when the template was applied.
    Type: String

Resources:
  GithubActionsOidcConnector:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
