---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Preloaded public keys'
Metadata:
  Template:
    Project: !Ref Project
    Revision: !Ref Revision

Parameters:
  Project:
    Description: An identifier for the project this stack is associated with.
    Type: String
  Revision:
    Description: The git short hash of the repo when the template was applied.
    Type: String

Resources:
  NinhursagKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: dominic@ninhursag
      PublicKeyMaterial: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE5rpMMLWs8oQXYtg9wXuvsb70O0vtPX+KEK1KiJAZVO
  EnkiKey:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: dominic@enki
      PublicKeyMaterial: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICzGL9KhRd2lKNuTZq1cK+4bkioGBkaMetfbzf/uuqTj
