---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policy, Role and InstanceProfile to allow an EC2 instance to be connected via SSM Session Manager'
Metadata:
  Template:
    Project: !Ref Project
    Revision: !Ref Revision

Parameters:
  Project:
    Description: An identifier for the project this stack is associated with.
    Type: String
  Revision:
    Description: The git short hash of the repo when the template was applied.
    Type: String

Resources:
  SessionManagerConnectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Allow EC2 instances to be connected via SSM Session Manager'
      ManagedPolicyName: SessionManagerConnectPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - ssmmessages:CreateControlChannel
            - ssmmessages:CreateDataChannel
            - ssmmessages:OpenControlChannel
            - ssmmessages:OpenDataChannel
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:DescribeAssociation
            - ssm:ListAssociations
            - ssm:UpdateAssociationStatus
            - ssm:UpdateInstanceAssociationStatus
            - ssm:UpdateInstanceInformation
            Resource: "*"

  SessionManagerRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Allow EC2 instances to be connected via SSM Session Manager'
      ManagedPolicyArns:
        - !Ref SessionManagerConnectPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Revision
          Value: !Ref Revision

  SessionManagerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: SessionManagerInstanceProfile
      Roles:
        - !Ref SessionManagerRole
